### PR TITLE
Updated checkout action in workflow to v3, to kill warnings

### PR DESCRIPTION
**Pull request by ahnlak**
Tiny change, to stop getting warnings from Github Actions every time I check something new in ;-)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
I don't know why the status checks are refusing to run here 😬

**Comment by Gadgetoid** [comment]
*looks at date*

💀

**Comment by ahnlak** [comment]
Hey, it's less than a year!

**Comment by Gadgetoid** [comment]
Merged via #19 since the CI went wonky (or probably expired *sigh* here)

Thank you!

**Pull request closed without merging**
